### ISSUE TITLE
Add exit keyword for CLI

### ISSUE THREAD

**Issue by rbpatt2019** [qorrect/PyPrql#16]
Current, typing exit in the CLI crashes with a massive wall of error text. Though not necessary, I think it would be cleaner to have `exit` close nicely, like `ctrl-c`.

**Comment by rbpatt2019** [comment]
Interestingly,
there already is an option for handling user input exit.
It calls `sys.exit(0)`,
which should exit cleanly.
Investigating why that isn't the case...

**Comment by qorrect** [comment]
That's weird , maybe python-prompt has a cleaner way to exit let me check

**Comment by rbpatt2019** [comment]
Got it. We just needed the completor to match exit to a list of empty strings, so that all the completion iterators work. Just submitted a PR for this.
