### ISSUE TITLE
Integer operations do not perform as expected

### ISSUE THREAD

**Issue by rbpatt2019** [qorrect/PyPrql#24]
The following query...

```
from employees | derive [gross_salary: salary + benefits_cost, net_salary: gross_salary - payroll_tax] | take 5
```

produces the following output...

```
┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ country ┃ salary  ┃ payroll_tax ┃ benefits_cost ┃ title     ┃ gross_salary ┃ net_salary ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ USA     │ 55,000  │ 1,200       │ 5,000         │ Developer │ 60           │ 59         │
│ USA     │ 55,000  │ 1,200       │ 5,000         │ Developer │ 60           │ 59         │
│ UK      │ 85,000  │ 1,400       │ 8000.0        │ Manager   │ 8085.0       │ 8084.0     │
│ USA     │ 155,000 │ 4,300       │ 15,000        │ Manager   │ 170          │ 166        │
│ USA     │ 255,000 │ 3450.0      │ 300.0         │ Manager   │ 555.0        │ -2895.0    │
└─────────┴─────────┴─────────────┴───────────────┴───────────┴──────────────┴────────────┘
```

which seems, well, wrong (at least to me!). There seems to be some truncating going on. Any number greater than a thousand and represented as an int (ie 55,000 but **not** 8000.0) is being truncated at the thousands place (ie 55,000 becomes 55) before operations. This produces the surprisingly small gross_salary and the surprisingly negative net_salary.

Since this seems to affect ints but not floats, I expect there's some type handling issue under the hood.

**Comment by rbpatt2019** [comment]
Just an update that all the involved columns (salary, payroll_tax, and benefits_cost) have the type in the column schema - REAL.

**Comment by qorrect** [comment]
@rbpatt2019 thats weird.  I updated all the rows to add .0 to them because I thought it might be garbage data ( I just halfhazardly created this )  but still the problem remains when using the '+' operator.

Ahh, it's the `,` , that is causing SQLite to handle those weirdly, taking them out gives expected results.  SQLite was just too polite to call me out for my garbage data.

**Comment by qorrect** [comment]
Is it possible, it interpreted the ',' as a '.' ?
